### ISSUE TITLE
ASdevsetup?

### ISSUE THREAD

**Issue by zenxedo** [toddaustin07/DC_alarmserver#1]
Where is the ASdevsetup script found?

**Comment by toddaustin07** [comment]
Hi there.  I haven't posted the files yet.  I've been focused on getting some bugs resolved in the core SDK, but the good news is those have been resolved and I'll be finally getting my base enablement package out of beta.  

If you are ready to give direct-connect alarmserver a try I'm happy to work with you to make that happen.  Give me a few days to  get things prepared.  In the meantime, let's switch over to email:  mine is rpi.smartthings@gmail.com.  Send me a message and let me know a little bit more about your setup so I can make sure things will go smoothly for you: 

1) Have you installed the base enablement package and gotten the example app running?
2) What Pi model and OS are you running?
3) Do you have alarmserver running now?  If so, how many zones and what types? (contact, motion, smoke, c02)

**Comment by toddaustin07** [comment]
All files are now posted, including ASdevsetup, so closing this issue.
